#!/bin/bash

declare -A vm_path   # create an associative array

vm_path["kala"]="/media/backup/VBox/kala/kali-linux-2023.1-virtualbox-amd64.vbox"

if [ $# -eq 0 ]; then
    echo "Please select VM name and start type."
    # echo "VM Names:"
    # for key in "${!vm_path[@]}"; do
    #     echo " - $key : ${vm_path[$key]}"
    # done

elif [ $# -eq 1 ]; then
    vm_name=$1
    path="${vm_path[$vm_name]}"
    vboxmanage startvm $path --type headless

elif [ $# -eq 2 ]; then
    vm_name=$1
    path="${vm_path[$vm_name]}"
    vboxmanage startvm $path --type $2

fi
